import pygame as PY
import random as RA
from constantes import pW, pH

PY.init()

# Tamaño de pantalla dinámico

screen = PY.display.set_mode((pW, pH))
PY.display.set_caption("Ecosistema Simulator")

class Bioma:
    def __init__(self, image_path, comida, agua):
        self.image = PY.image.load(image_path)
        self.comida = comida
        self.agua = agua

class Desierto(Bioma):
    def __init__(self):
        super().__init__("Proyecto/imagenes/arena.png", RA.randint(0, 1), 0)

class Agua(Bioma):
    def __init__(self):
        super().__init__("Proyecto/imagenes/agua.png", 0, RA.randint(0, 5))

class Tierra(Bioma):
    def __init__(self):
        super().__init__("Proyecto/imagenes/tierra.png", RA.randint(0, 5), 0)



bioma_dict = {
    "A": Agua(),
    "D": Desierto(),
    "T": Tierra()
}

patron_biomas = [
    "TTTTTTTTTTTTTTTTTTAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAADDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAADDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTAAAAAAAAAADDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTAAAAAADDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTTAAAAAADDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTTAAAAAAADDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTAAAAAAAADDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTAAAAAAAADDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTAAAAAAAADDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTAAAAADDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTTAAAAAADDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTTTAAAAAAAAADDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTAAAAAAAAAADDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTTTAAAAAAAAADDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTAAAAAAAAAAAADDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAADDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAADDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTAAAAAAAAAAAADDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAADDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTAAAAAAAAAADDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAADDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTAAAAAAAAAAAADDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAADDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAADDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTAAAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTAAAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTAAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDD",
]

matriz_biomas = []
for fila_patron in patron_biomas:
    fila_biomas = []
    for letra in fila_patron:
        if letra == "D":
            fila_biomas.append(Desierto())
        elif letra == "A":
            fila_biomas.append(Agua())
        elif letra == "T":
            fila_biomas.append(Tierra())
    matriz_biomas.append(fila_biomas)

