import pygame as PY
import random as RA

PY.init()

# Tamaño de pantalla dinámico
pW = 800
pH = 800
screen = PY.display.set_mode((pW, pH))
PY.display.set_caption("Ecosistema Simulator")

class Bioma:
    def __init__(self, image_path):
        self.image = PY.image.load(image_path)

class Desierto(Bioma):
    def __init__(self):
        super().__init__("Proyecto/arena.png")

class Agua(Bioma):
    def __init__(self):
        super().__init__("Proyecto/agua.png")

class Tierra(Bioma):
    def __init__(self):
        super().__init__("Proyecto/tierra.png")


bioma_dict = {
    "A": Agua(),
    "D": Desierto(),
    "T": Tierra()
}

patron_biomas = [
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "DTDTDTDTDTDTDTDTADAADAADAADAADAADAADAADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "DTDTDTDTDTDTDTDTADAADAADAADAADAADAADAADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "DTDTDTDTDTDTDTDTADAADAADAADAADAADAADAADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "DTDTDTDTDTDTDTDTADAADAADAADAADAADAADAADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "DTDTDTDTDTDTDTDTADAADAADAADAADAADAADAADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "DTDTDTDTDTDTDTDTADAADAADAADAADAADAADAADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "DTDTDTDTDTDTDTDTADAADAADAADAADAADAADAADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "DTDTDTDTDTDTDTDTADAADAADAADAADAADAADAADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "DTDTDTDTDTDTDTDTADAADAADAADAADAADAADAADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
    "DTDTDTDTDTDTDTDTADAADAADAADAADAADAADAADAADAADAADAA",
    "AAADADAADADADAADAADAAAADADAADADADAADAADADADAADAADA",
    "ATTTTTTTTTTTTTTTDADAADAADADADAADAADADADAADAADAADAA",
]
