import pygame as PY

PY.init()

# Tamaño de pantalla dinámico
pW = 800
pH = 800
screen = PY.display.set_mode((pW, pH))
PY.display.set_caption("Ecosistema Simulator")

class Bioma:
    def __init__(self, image_path):
        self.image = PY.image.load(image_path)

class Desierto(Bioma):
    def __init__(self):
        super().__init__("Proyecto/arena.png")

class Agua(Bioma):
    def __init__(self):
        super().__init__("Proyecto/agua.png")

class Tierra(Bioma):
    def __init__(self):
        super().__init__("Proyecto/tierra.png")

class Nieve(Bioma):
    def __init__(self):
        super().__init__("Proyecto/nieve.png")

bioma_dict = {
    "A": Agua(),
    "D": Desierto(),
    "T": Tierra(),
    "N": Nieve()
}

patron_biomas = [
    "TTTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTAAAAADDDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTTAAAAADDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTTTAAAADDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTAAAAADDDDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTTAAAAAADDDDDDDDDDDDDDDDDDDDD",
    "TTTTTTTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "TTTTTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "TTTTTTTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "TTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "TTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "TTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "TTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "TTTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "TTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "TTTTTTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNAAAAAAAAAAAAAA",
    "TTTTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNAAAAAAAA",
    "TTTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "TTTTTTTTTTTTTTTTTAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
]
